/**
 * Preset Themes
 *
 * Built-in themes that ship with the app.
 * Users can switch between these instantly without DB access.
 * These also serve as seeds for the Supabase themes table.
 */

import { SCHEMA_VERSION } from './themeDefaults';

// ── 🌊 Ocean (Default Dark Glassmorphism) ─────────────────
export const OCEAN = {
  schemaVersion: SCHEMA_VERSION,
  name: 'Ocean',
  description: 'Deep sea dark theme with frosted glass effects',
  author: 'system',
  colors: {
    'primary': '#3c83f6',
    'primary-container': '#004c6a',
    'primary-dim': '#2563eb',
    'primary-fixed': '#2db7f2',
    'primary-fixed-dim': '#05a9e3',
    'on-primary': '#003549',
    'on-primary-container': '#c4e7ff',
    'on-primary-fixed': '#001e2d',
    'on-primary-fixed-variant': '#004c6a',
    'secondary': '#ff8c42',
    'secondary-container': '#504500',
    'secondary-dim': '#e0742e',
    'secondary-fixed': '#fcdf46',
    'secondary-fixed-dim': '#e0c42e',
    'on-secondary': '#373100',
    'on-secondary-container': '#ffe070',
    'on-secondary-fixed': '#211b00',
    'on-secondary-fixed-variant': '#504500',
    'tertiary': '#10b981',
    'tertiary-container': '#005048',
    'tertiary-dim': '#059669',
    'tertiary-fixed': '#91feef',
    'tertiary-fixed-dim': '#4ce0d1',
    'on-tertiary': '#003731',
    'on-tertiary-container': '#b0fff0',
    'on-tertiary-fixed': '#00201c',
    'on-tertiary-fixed-variant': '#005048',
    'error': '#ef4444',
    'error-container': '#93000a',
    'error-dim': '#dc2626',
    'on-error': '#690005',
    'on-error-container': '#ffdad6',
    'surface': '#0d111b',
    'surface-variant': '#1e293b',
    'surface-dim': '#0a0e17',
    'surface-bright': '#2a3548',
    'surface-tint': '#3c83f6',
    'surface-container': '#141927',
    'surface-container-low': '#111520',
    'surface-container-high': '#1e293b',
    'surface-container-lowest': '#080b12',
    'surface-container-highest': '#283343',
    'on-surface': '#f8fafc',
    'on-surface-variant': '#cbd5e1',
    'background': '#0d111b',
    'on-background': '#f8fafc',
    'outline': 'rgba(255, 255, 255, 0.08)',
    'outline-variant': 'rgba(255, 255, 255, 0.04)',
    'inverse-surface': '#e2e8f0',
    'inverse-on-surface': '#1e293b',
    'inverse-primary': '#006286',
  },
  extended: {
    glass: { bg: 'rgba(255,255,255,0.03)', nav: 'rgba(13,17,27,0.8)', blur: 'blur(12px)' },
    shadow: { premium: '0 10px 25px -5px rgba(0,0,0,0.3), 0 8px 10px -6px rgba(0,0,0,0.3)' },
    status: { ongoing: '#3b82f6', upcoming: '#10b981', soon: '#f59e0b', passed: '#94a3b8' },
    transit: { flight: '#4FC3F7', train: '#9E9E9E', bus: '#FF8F00', ship: '#1E88E5', drive: '#3b82f6', walk: '#10b981' },
    hotel: { checkin: '#22c55e', checkout: '#ef4444', line: '#f59e0b' },
    category: { food: '#f97316', attraction: '#8b5cf6', nature: '#10b981', shopping: '#ec4899' },
    textMuted: '#94a3b8',
    timelineDefault: '#5b7a99',
  },
  typography: {
    headline: "'Manrope', 'Plus Jakarta Sans', sans-serif",
    body: "'Manrope', 'Plus Jakarta Sans', 'Noto Sans SC', sans-serif",
    label: "'Lexend', 'Plus Jakarta Sans', sans-serif",
  },
  shape: { cornerMedium: '1rem', cornerLarge: '2rem', cornerExtraLarge: '3rem', cornerFull: '9999px' },
  layout: {
    variant: 'glass',
    card: { flip: true, elevation: 'none', backdrop: true },
    timeline: { dotSize: '8px', dotStyle: 'filled', lineStyle: 'dashed', lineWidth: '2px' },
    transit: { display: 'collapsible' },
    navigation: { position: 'top', style: 'glass' },
    header: { style: 'sticky-bar', showHero: false },
  },
};

// ── 🌸 Sakura ─────────────────────────────────────────────
export const SAKURA = {
  schemaVersion: SCHEMA_VERSION,
  name: 'Sakura',
  description: 'Cherry blossom pink theme inspired by Japanese spring',
  author: 'system',
  colors: {
    'primary': '#f472b6',
    'primary-container': '#831843',
    'primary-dim': '#ec4899',
    'primary-fixed': '#fbcfe8',
    'primary-fixed-dim': '#f9a8d4',
    'on-primary': '#4a0626',
    'on-primary-container': '#fce7f3',
    'on-primary-fixed': '#3b0518',
    'on-primary-fixed-variant': '#831843',
    'secondary': '#c084fc',
    'secondary-container': '#581c87',
    'secondary-dim': '#a855f7',
    'secondary-fixed': '#e9d5ff',
    'secondary-fixed-dim': '#d8b4fe',
    'on-secondary': '#3b0764',
    'on-secondary-container': '#f3e8ff',
    'on-secondary-fixed': '#2e0553',
    'on-secondary-fixed-variant': '#581c87',
    'tertiary': '#fb923c',
    'tertiary-container': '#7c2d12',
    'tertiary-dim': '#f97316',
    'tertiary-fixed': '#fed7aa',
    'tertiary-fixed-dim': '#fdba74',
    'on-tertiary': '#431407',
    'on-tertiary-container': '#ffedd5',
    'on-tertiary-fixed': '#341005',
    'on-tertiary-fixed-variant': '#7c2d12',
    'error': '#fb7185',
    'error-container': '#881337',
    'error-dim': '#f43f5e',
    'on-error': '#4c0519',
    'on-error-container': '#ffe4e6',
    'surface': '#1a0a12',
    'surface-variant': '#2d1520',
    'surface-dim': '#140810',
    'surface-bright': '#3d1a2e',
    'surface-tint': '#f472b6',
    'surface-container': '#1f0e18',
    'surface-container-low': '#1c0c15',
    'surface-container-high': '#2d1520',
    'surface-container-lowest': '#10060c',
    'surface-container-highest': '#3a1828',
    'on-surface': '#fce7f3',
    'on-surface-variant': '#f9a8d4',
    'background': '#1a0a12',
    'on-background': '#fce7f3',
    'outline': 'rgba(244, 114, 182, 0.15)',
    'outline-variant': 'rgba(244, 114, 182, 0.06)',
    'inverse-surface': '#fce7f3',
    'inverse-on-surface': '#1a0a12',
    'inverse-primary': '#be185d',
  },
  extended: {
    glass: { bg: 'rgba(244,114,182,0.04)', nav: 'rgba(26,10,18,0.85)', blur: 'blur(14px)' },
    shadow: { premium: '0 10px 25px -5px rgba(190,24,93,0.2), 0 8px 10px -6px rgba(0,0,0,0.3)' },
    status: { ongoing: '#f472b6', upcoming: '#a78bfa', soon: '#fb923c', passed: '#9ca3af' },
    transit: { flight: '#e879f9', train: '#a1a1aa', bus: '#fb923c', ship: '#818cf8', drive: '#f472b6', walk: '#a78bfa' },
    hotel: { checkin: '#a78bfa', checkout: '#fb7185', line: '#c084fc' },
    category: { food: '#fb923c', attraction: '#c084fc', nature: '#a78bfa', shopping: '#f472b6' },
    textMuted: '#9ca3af',
    timelineDefault: '#be6b8a',
  },
  typography: {
    headline: "'Manrope', 'Plus Jakarta Sans', sans-serif",
    body: "'Manrope', 'Plus Jakarta Sans', 'Noto Sans SC', sans-serif",
    label: "'Lexend', 'Plus Jakarta Sans', sans-serif",
  },
  shape: { cornerMedium: '1rem', cornerLarge: '2rem', cornerExtraLarge: '3rem', cornerFull: '9999px' },
  layout: {
    variant: 'glass',
    card: { flip: true, elevation: 'none', backdrop: true },
    timeline: { dotSize: '8px', dotStyle: 'filled', lineStyle: 'dashed', lineWidth: '2px' },
    transit: { display: 'collapsible' },
    navigation: { position: 'top', style: 'glass' },
    header: { style: 'sticky-bar', showHero: false },
  },
};

// ── 🌿 Forest ─────────────────────────────────────────────
export const FOREST = {
  schemaVersion: SCHEMA_VERSION,
  name: 'Forest',
  description: 'Deep emerald green theme inspired by ancient woodlands',
  author: 'system',
  colors: {
    'primary': '#34d399',
    'primary-container': '#064e3b',
    'primary-dim': '#10b981',
    'primary-fixed': '#a7f3d0',
    'primary-fixed-dim': '#6ee7b7',
    'on-primary': '#022c22',
    'on-primary-container': '#d1fae5',
    'on-primary-fixed': '#012118',
    'on-primary-fixed-variant': '#064e3b',
    'secondary': '#fbbf24',
    'secondary-container': '#713f12',
    'secondary-dim': '#f59e0b',
    'secondary-fixed': '#fef08a',
    'secondary-fixed-dim': '#fde047',
    'on-secondary': '#422006',
    'on-secondary-container': '#fef9c3',
    'on-secondary-fixed': '#3a1a04',
    'on-secondary-fixed-variant': '#713f12',
    'tertiary': '#67e8f9',
    'tertiary-container': '#164e63',
    'tertiary-dim': '#22d3ee',
    'tertiary-fixed': '#a5f3fc',
    'tertiary-fixed-dim': '#67e8f9',
    'on-tertiary': '#083344',
    'on-tertiary-container': '#cffafe',
    'on-tertiary-fixed': '#062c3b',
    'on-tertiary-fixed-variant': '#164e63',
    'error': '#f87171',
    'error-container': '#7f1d1d',
    'error-dim': '#ef4444',
    'on-error': '#450a0a',
    'on-error-container': '#fee2e2',
    'surface': '#071a12',
    'surface-variant': '#14332a',
    'surface-dim': '#051208',
    'surface-bright': '#1a4a38',
    'surface-tint': '#34d399',
    'surface-container': '#0c2418',
    'surface-container-low': '#091e14',
    'surface-container-high': '#14332a',
    'surface-container-lowest': '#030e08',
    'surface-container-highest': '#1c4034',
    'on-surface': '#ecfdf5',
    'on-surface-variant': '#a7f3d0',
    'background': '#071a12',
    'on-background': '#ecfdf5',
    'outline': 'rgba(52, 211, 153, 0.12)',
    'outline-variant': 'rgba(52, 211, 153, 0.05)',
    'inverse-surface': '#d1fae5',
    'inverse-on-surface': '#064e3b',
    'inverse-primary': '#047857',
  },
  extended: {
    glass: { bg: 'rgba(52,211,153,0.04)', nav: 'rgba(7,26,18,0.85)', blur: 'blur(12px)' },
    shadow: { premium: '0 10px 25px -5px rgba(4,120,87,0.2), 0 8px 10px -6px rgba(0,0,0,0.3)' },
    status: { ongoing: '#34d399', upcoming: '#67e8f9', soon: '#fbbf24', passed: '#9ca3af' },
    transit: { flight: '#67e8f9', train: '#a1a1aa', bus: '#fbbf24', ship: '#38bdf8', drive: '#34d399', walk: '#86efac' },
    hotel: { checkin: '#86efac', checkout: '#f87171', line: '#fbbf24' },
    category: { food: '#fbbf24', attraction: '#67e8f9', nature: '#86efac', shopping: '#f0abfc' },
    textMuted: '#6b8f80',
    timelineDefault: '#4a9e7e',
  },
  typography: {
    headline: "'Manrope', 'Plus Jakarta Sans', sans-serif",
    body: "'Manrope', 'Plus Jakarta Sans', 'Noto Sans SC', sans-serif",
    label: "'Lexend', 'Plus Jakarta Sans', sans-serif",
  },
  shape: { cornerMedium: '1rem', cornerLarge: '2rem', cornerExtraLarge: '3rem', cornerFull: '9999px' },
  layout: {
    variant: 'glass',
    card: { flip: true, elevation: 'none', backdrop: true },
    timeline: { dotSize: '8px', dotStyle: 'filled', lineStyle: 'dashed', lineWidth: '2px' },
    transit: { display: 'collapsible' },
    navigation: { position: 'top', style: 'glass' },
    header: { style: 'sticky-bar', showHero: false },
  },
};

// ── 🔥 Ember ──────────────────────────────────────────────
export const EMBER = {
  schemaVersion: SCHEMA_VERSION,
  name: 'Ember',
  description: 'Warm amber and volcanic red theme',
  author: 'system',
  colors: {
    'primary': '#fb923c',
    'primary-container': '#7c2d12',
    'primary-dim': '#f97316',
    'primary-fixed': '#fed7aa',
    'primary-fixed-dim': '#fdba74',
    'on-primary': '#431407',
    'on-primary-container': '#ffedd5',
    'on-primary-fixed': '#341005',
    'on-primary-fixed-variant': '#7c2d12',
    'secondary': '#fbbf24',
    'secondary-container': '#713f12',
    'secondary-dim': '#f59e0b',
    'secondary-fixed': '#fef08a',
    'secondary-fixed-dim': '#fde047',
    'on-secondary': '#422006',
    'on-secondary-container': '#fef9c3',
    'on-secondary-fixed': '#3a1a04',
    'on-secondary-fixed-variant': '#713f12',
    'tertiary': '#f87171',
    'tertiary-container': '#7f1d1d',
    'tertiary-dim': '#ef4444',
    'tertiary-fixed': '#fecaca',
    'tertiary-fixed-dim': '#fca5a5',
    'on-tertiary': '#450a0a',
    'on-tertiary-container': '#fee2e2',
    'on-tertiary-fixed': '#3b0707',
    'on-tertiary-fixed-variant': '#7f1d1d',
    'error': '#f87171',
    'error-container': '#7f1d1d',
    'error-dim': '#ef4444',
    'on-error': '#450a0a',
    'on-error-container': '#fee2e2',
    'surface': '#1a0e08',
    'surface-variant': '#33200f',
    'surface-dim': '#140a05',
    'surface-bright': '#4d3018',
    'surface-tint': '#fb923c',
    'surface-container': '#231508',
    'surface-container-low': '#1e1108',
    'surface-container-high': '#33200f',
    'surface-container-lowest': '#0f0704',
    'surface-container-highest': '#3d2814',
    'on-surface': '#fff7ed',
    'on-surface-variant': '#fdba74',
    'background': '#1a0e08',
    'on-background': '#fff7ed',
    'outline': 'rgba(251, 146, 60, 0.15)',
    'outline-variant': 'rgba(251, 146, 60, 0.06)',
    'inverse-surface': '#ffedd5',
    'inverse-on-surface': '#7c2d12',
    'inverse-primary': '#c2410c',
  },
  extended: {
    glass: { bg: 'rgba(251,146,60,0.04)', nav: 'rgba(26,14,8,0.85)', blur: 'blur(12px)' },
    shadow: { premium: '0 10px 25px -5px rgba(194,65,12,0.2), 0 8px 10px -6px rgba(0,0,0,0.3)' },
    status: { ongoing: '#fb923c', upcoming: '#fbbf24', soon: '#f87171', passed: '#9ca3af' },
    transit: { flight: '#fbbf24', train: '#a1a1aa', bus: '#f87171', ship: '#fb923c', drive: '#fbbf24', walk: '#fde047' },
    hotel: { checkin: '#fbbf24', checkout: '#f87171', line: '#fb923c' },
    category: { food: '#f87171', attraction: '#fbbf24', nature: '#fb923c', shopping: '#f0abfc' },
    textMuted: '#a08060',
    timelineDefault: '#c47a3a',
  },
  typography: {
    headline: "'Manrope', 'Plus Jakarta Sans', sans-serif",
    body: "'Manrope', 'Plus Jakarta Sans', 'Noto Sans SC', sans-serif",
    label: "'Lexend', 'Plus Jakarta Sans', sans-serif",
  },
  shape: { cornerMedium: '1rem', cornerLarge: '2rem', cornerExtraLarge: '3rem', cornerFull: '9999px' },
  layout: {
    variant: 'glass',
    card: { flip: true, elevation: 'none', backdrop: true },
    timeline: { dotSize: '8px', dotStyle: 'filled', lineStyle: 'dashed', lineWidth: '2px' },
    transit: { display: 'collapsible' },
    navigation: { position: 'top', style: 'glass' },
    header: { style: 'sticky-bar', showHero: false },
  },
};

// ── 🌙 Midnight ───────────────────────────────────────────
export const MIDNIGHT = {
  schemaVersion: SCHEMA_VERSION,
  name: 'Midnight',
  description: 'Deep indigo purple theme with cosmic vibes',
  author: 'system',
  colors: {
    'primary': '#818cf8',
    'primary-container': '#3730a3',
    'primary-dim': '#6366f1',
    'primary-fixed': '#c7d2fe',
    'primary-fixed-dim': '#a5b4fc',
    'on-primary': '#1e1b4b',
    'on-primary-container': '#e0e7ff',
    'on-primary-fixed': '#16143b',
    'on-primary-fixed-variant': '#3730a3',
    'secondary': '#f0abfc',
    'secondary-container': '#701a75',
    'secondary-dim': '#e879f9',
    'secondary-fixed': '#fae8ff',
    'secondary-fixed-dim': '#f5d0fe',
    'on-secondary': '#4a044e',
    'on-secondary-container': '#fdf4ff',
    'on-secondary-fixed': '#3b0340',
    'on-secondary-fixed-variant': '#701a75',
    'tertiary': '#67e8f9',
    'tertiary-container': '#164e63',
    'tertiary-dim': '#22d3ee',
    'tertiary-fixed': '#a5f3fc',
    'tertiary-fixed-dim': '#67e8f9',
    'on-tertiary': '#083344',
    'on-tertiary-container': '#cffafe',
    'on-tertiary-fixed': '#062c3b',
    'on-tertiary-fixed-variant': '#164e63',
    'error': '#fca5a5',
    'error-container': '#7f1d1d',
    'error-dim': '#f87171',
    'on-error': '#450a0a',
    'on-error-container': '#fee2e2',
    'surface': '#0c0a1a',
    'surface-variant': '#1e1b3a',
    'surface-dim': '#080618',
    'surface-bright': '#2d2952',
    'surface-tint': '#818cf8',
    'surface-container': '#121028',
    'surface-container-low': '#0f0d22',
    'surface-container-high': '#1e1b3a',
    'surface-container-lowest': '#060510',
    'surface-container-highest': '#282548',
    'on-surface': '#e0e7ff',
    'on-surface-variant': '#a5b4fc',
    'background': '#0c0a1a',
    'on-background': '#e0e7ff',
    'outline': 'rgba(129, 140, 248, 0.12)',
    'outline-variant': 'rgba(129, 140, 248, 0.05)',
    'inverse-surface': '#e0e7ff',
    'inverse-on-surface': '#1e1b4b',
    'inverse-primary': '#4338ca',
  },
  extended: {
    glass: { bg: 'rgba(129,140,248,0.04)', nav: 'rgba(12,10,26,0.85)', blur: 'blur(14px)' },
    shadow: { premium: '0 10px 25px -5px rgba(67,56,202,0.2), 0 8px 10px -6px rgba(0,0,0,0.3)' },
    status: { ongoing: '#818cf8', upcoming: '#67e8f9', soon: '#f0abfc', passed: '#9ca3af' },
    transit: { flight: '#67e8f9', train: '#a1a1aa', bus: '#f0abfc', ship: '#818cf8', drive: '#a5b4fc', walk: '#67e8f9' },
    hotel: { checkin: '#67e8f9', checkout: '#fca5a5', line: '#f0abfc' },
    category: { food: '#f0abfc', attraction: '#818cf8', nature: '#67e8f9', shopping: '#fca5a5' },
    textMuted: '#7c7fa0',
    timelineDefault: '#6568a8',
  },
  typography: {
    headline: "'Manrope', 'Plus Jakarta Sans', sans-serif",
    body: "'Manrope', 'Plus Jakarta Sans', 'Noto Sans SC', sans-serif",
    label: "'Lexend', 'Plus Jakarta Sans', sans-serif",
  },
  shape: { cornerMedium: '1rem', cornerLarge: '2rem', cornerExtraLarge: '3rem', cornerFull: '9999px' },
  layout: {
    variant: 'glass',
    card: { flip: true, elevation: 'none', backdrop: true },
    timeline: { dotSize: '8px', dotStyle: 'filled', lineStyle: 'dashed', lineWidth: '2px' },
    transit: { display: 'collapsible' },
    navigation: { position: 'top', style: 'glass' },
    header: { style: 'sticky-bar', showHero: false },
  },
};

// ── ☁️ Clean (Light M3 — Figma Tokyo Design) ──────────────
export const CLEAN = {
  schemaVersion: SCHEMA_VERSION,
  name: 'Clean',
  description: 'Minimal light theme with soft grays and teal accents',
  author: 'system',
  colors: {
    'primary': '#4d556a',
    'primary-container': '#656d84',
    'primary-dim': '#3f465c',
    'primary-fixed': '#dae2fd',
    'primary-fixed-dim': '#bec6e0',
    'on-primary': '#ffffff',
    'on-primary-container': '#edf0ff',
    'on-primary-fixed': '#131b2e',
    'on-primary-fixed-variant': '#3f465c',
    'secondary': '#515f74',
    'secondary-container': '#d5e3fd',
    'secondary-dim': '#3a485c',
    'secondary-fixed': '#d5e3fd',
    'secondary-fixed-dim': '#b9c7e0',
    'on-secondary': '#ffffff',
    'on-secondary-container': '#57657b',
    'on-secondary-fixed': '#0d1c2f',
    'on-secondary-fixed-variant': '#3a485c',
    'tertiary': '#006058',
    'tertiary-container': '#007b71',
    'tertiary-dim': '#005049',
    'tertiary-fixed': '#89f5e7',
    'tertiary-fixed-dim': '#6bd8cb',
    'on-tertiary': '#ffffff',
    'on-tertiary-container': '#b3fff3',
    'on-tertiary-fixed': '#00201d',
    'on-tertiary-fixed-variant': '#005049',
    'error': '#ba1a1a',
    'error-container': '#ffdad6',
    'error-dim': '#93000a',
    'on-error': '#ffffff',
    'on-error-container': '#93000a',
    'surface': '#f7f9fb',
    'surface-variant': '#e0e3e5',
    'surface-dim': '#d8dadc',
    'surface-bright': '#f7f9fb',
    'surface-tint': '#565e74',
    'surface-container': '#eceef0',
    'surface-container-low': '#f2f4f6',
    'surface-container-high': '#e6e8ea',
    'surface-container-lowest': '#ffffff',
    'surface-container-highest': '#e0e3e5',
    'on-surface': '#191c1e',
    'on-surface-variant': '#434655',
    'background': '#f7f9fb',
    'on-background': '#191c1e',
    'outline': '#737686',
    'outline-variant': '#c3c6d7',
    'inverse-surface': '#2d3133',
    'inverse-on-surface': '#eff1f3',
    'inverse-primary': '#bec6e0',
  },
  extended: {
    glass: { bg: 'rgba(77,85,106,0.04)', nav: 'rgba(247,249,251,0.85)', blur: 'blur(12px)' },
    shadow: { premium: '0 4px 16px -4px rgba(25,28,30,0.08), 0 2px 6px -2px rgba(25,28,30,0.06)' },
    status: { ongoing: '#4d556a', upcoming: '#006058', soon: '#ba6900', passed: '#737686' },
    transit: { flight: '#006058', train: '#737686', bus: '#ba6900', ship: '#4d556a', drive: '#515f74', walk: '#006058' },
    hotel: { checkin: '#006058', checkout: '#ba1a1a', line: '#ba6900' },
    category: { food: '#ba6900', attraction: '#4d556a', nature: '#006058', shopping: '#7b5ea7' },
    textMuted: '#737686',
    timelineDefault: '#9296a5',
  },
  typography: {
    headline: "'Manrope', 'Plus Jakarta Sans', sans-serif",
    body: "'Inter', 'Plus Jakarta Sans', 'Noto Sans SC', sans-serif",
    label: "'Inter', 'Plus Jakarta Sans', sans-serif",
  },
  shape: { cornerMedium: '0.75rem', cornerLarge: '1rem', cornerExtraLarge: '1.5rem', cornerFull: '9999px' },
  layout: {
    variant: 'clean',
    card: { flip: false, elevation: 'sm', backdrop: false },
    timeline: { dotSize: '24px', dotStyle: 'hollow', lineStyle: 'dashed', lineWidth: '2px' },
    transit: { display: 'inline' },
    navigation: { position: 'bottom', style: 'flat' },
    header: { style: 'transparent', showHero: true },
  },
};

// ── All Presets ────────────────────────────────────────────
export const PRESET_THEMES = [
  { id: 'ocean',    theme: OCEAN,    emoji: '🌊' },
  { id: 'sakura',   theme: SAKURA,   emoji: '🌸' },
  { id: 'forest',   theme: FOREST,   emoji: '🌿' },
  { id: 'ember',    theme: EMBER,    emoji: '🔥' },
  { id: 'midnight', theme: MIDNIGHT, emoji: '🌙' },
  { id: 'clean',    theme: CLEAN,    emoji: '☁️' },
];
